spring:
 application:
  name: ${APPLICATION_NAME:auth-server}
 jackson:
   serialization:
     WRITE_NULL_MAP_VALUES: false

auth:
 secret:
  ttl: 2678400
 token:
  ttl: 86400
  issuer: "http://ratauth.ru"
 refresh_token:
  ttl: 36000
 code:
  ttl: 86400
 session:
  check_threads: 10
  check_interval: 300