spring:
 application:
  name: ${APPLICATION_NAME:auth-server}
 jackson:
   serialization:
     WRITE_NULL_MAP_VALUES: false

auth:
  signature:
    issuer: "http://ratauth.ru"
    masterSecret: "cnlqV2hVQml3aWdrc1RqWXBSaFpma3l5enhNVU1TS1A="
  session:
    check_interval: 300
    check_threads: 10